FROM python:3.11

WORKDIR .

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY . .

EXPOSE 8000

CMD ["python","-m","app.main"]

# ENTRYPOINT ["uvicorn","app.main:app","--port","8000","--host","0.0.0.0"]